### ISSUE TITLE
Changelog in KSP AVC comes up with HTML instead of plaintext.

### ISSUE THREAD

**Issue by ProgrammerFailure** [linuxgurugamer/REKT#10]
When I open KSP with this mod (0.4.8.2) and KSP AVC, it shows a new version out. When I select the changelog button in KSP AVC, I get a window with a bunch of HTML text.

**Comment by linuxgurugamer** [comment]
Would be nice to see a snapshot of the window

**Comment by ProgrammerFailure** [comment]
Here is a screenshot:
![image](https://github.com/linuxgurugamer/REKT/assets/122328786/ec9e9373-27af-47b1-9a87-fae44ec2d192)
And a image of the KSP AVC screen:
![image](https://github.com/linuxgurugamer/REKT/assets/122328786/8e66cad6-be93-402b-836d-17f12963d149)

**Comment by linuxgurugamer** [comment]
Ok,I'll take a look, although this is a KSP-AVC problem, not a REKT problem, should have been reported on the KSP-AVC thread

**Comment by linuxgurugamer** [comment]
Oh, that's not the KSP-AVC screen, that's the changelog mod (Kerbal Changelog), and REKT doesn't have anything to do with that att all.  The KSP-AVC screen is woring fine, it's the second pic you showed

**Comment by ProgrammerFailure** [comment]
@linuxgurugamer 
So should I report this on the Kerbal Changelog mod?
